### ISSUE TITLE
K8s prometheus yaml files

### ISSUE THREAD

**Issue by ericcgu** [DoomHammer/pluralsight-opensource-your-project-on-github#6]
can you share the yaml files? @DoomHammer 

https://app.pluralsight.com/course-player?clipId=c2410471-45bf-44ab-81f6-ae4e93995f56

**Comment by DoomHammer** [comment]
Thanks for your feedback, @ericcgu !

What you're looking for is probably https://github.com/DoomHammer/pluralsight-managing-advanced-kubernetes-logging-and-tracing .

Let me know if this solves your issue.

**Comment by ericcgu** [comment]
yes thanks. it would nice if pluralsight included that instead of just the
pdf links. thanks

**Comment by DoomHammer** [comment]
It's my fault, really. Should've mentioned the repo in the course.
